[phases.setup]
nixPkgs = [
    "chromium", 
    "nss", 
    "nspr", 
    "atk", 
    "cups", 
    "libxcomposite", 
    "libxdamage", 
    "libxrandr", 
    "libxkbcommon", 
    "pango", 
    "cairo"
]

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"